Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120  
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes      
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
